CREATE TABLE user (
  id       bigint generated BY DEFAULT AS IDENTITY,
  version  INTEGER NOT NULL,
  email    VARCHAR(255),
  login    VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  PRIMARY KEY (id)
);


