create table users_roles (
  id          bigint generated by default as identity,
  user_id     int,
  role_id     int,
  FOREIGN KEY (user_id) REFERENCES user(id),
  FOREIGN KEY (role_id) REFERENCES role(id),
  primary key (id)
);
